include:
  admin: github.com/backlift/backlift-admin

themes:
  cerulean: 
    cerulean: raw.github.com/thomaspark/bootswatch/gh-pages/cerulean/bootstrap.css
  spruce:
    spruce: raw.github.com/thomaspark/bootswatch/gh-pages/spruce/bootstrap.css 
