styles:
- /libraries/styles/bootstrap.css
- /theme-*/**/*.css
- /libraries/styles/bootstrap-responsive.css

scripts:
- /libraries/scripts/underscore.js
- /libraries/scripts/jquery.js
- /libraries/scripts/backbone.js
- /libraries/**/*.js
- /scripts/**/*.js

autoroute: yes

include:
  libraries: 
  - github.com/backlift/backbone-bundle/tree/20130406
  - github.com/backlift/bootstrap-bundle/tree/20130406
  libraries/scripts: 
  - gist.github.com/backlift/5325013 # backlift-reloader.js
  - gist.github.com/backlift/5334085 # backlift-commonview.js 

packages:
  include:
    libraries: 
    - github.com/backlift/backbone-bundle/tree/20130406
    - github.com/backlift/bootstrap-bundle/tree/20130406
    libraries/scripts: 
    - gist.github.com/backlift/5325013 # backlift-reloader.js
    - gist.github.com/backlift/5334085 # backlift-commonview.js 
  amelia:
    theme-amelia: raw.github.com/thomaspark/bootswatch/gh-pages/amelia/bootstrap.css
  cerulean: 
    theme-cerulean: raw.github.com/thomaspark/bootswatch/gh-pages/cerulean/bootstrap.css
  readable:
    theme-readable: raw.github.com/thomaspark/bootswatch/gh-pages/readable/bootstrap.css
  spruce:
    theme-spruce: raw.github.com/thomaspark/bootswatch/gh-pages/spruce/bootstrap.css 
  superhero:
    theme-superhero: raw.github.com/thomaspark/bootswatch/gh-pages/superhero/bootstrap.css
  simplex:
    theme-simplex: raw.github.com/thomaspark/bootswatch/gh-pages/simplex/bootstrap.css
  slate:
    theme-slate: raw.github.com/thomaspark/bootswatch/gh-pages/slate/bootstrap.css

require:
- include  

import:
- /helloworld.json